// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/acai-travel/tech-challenge/internal/chat/assistant (interfaces: completionsAPI)
//
// Generated by this command:
//
//	mockgen -destination=mock_completions_test.go -package=assistant github.com/acai-travel/tech-challenge/internal/chat/assistant completionsAPI
//

// Package assistant is a generated GoMock package.
package assistant

import (
	context "context"
	reflect "reflect"

	openai "github.com/openai/openai-go/v2"
	option "github.com/openai/openai-go/v2/option"
	gomock "go.uber.org/mock/gomock"
)

// MockcompletionsAPI is a mock of completionsAPI interface.
type MockcompletionsAPI struct {
	ctrl     *gomock.Controller
	recorder *MockcompletionsAPIMockRecorder
	isgomock struct{}
}

// MockcompletionsAPIMockRecorder is the mock recorder for MockcompletionsAPI.
type MockcompletionsAPIMockRecorder struct {
	mock *MockcompletionsAPI
}

// NewMockcompletionsAPI creates a new mock instance.
func NewMockcompletionsAPI(ctrl *gomock.Controller) *MockcompletionsAPI {
	mock := &MockcompletionsAPI{ctrl: ctrl}
	mock.recorder = &MockcompletionsAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcompletionsAPI) EXPECT() *MockcompletionsAPIMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *MockcompletionsAPI) New(ctx context.Context, body openai.ChatCompletionNewParams, opts ...option.RequestOption) (*openai.ChatCompletion, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "New", varargs...)
	ret0, _ := ret[0].(*openai.ChatCompletion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// New indicates an expected call of New.
func (mr *MockcompletionsAPIMockRecorder) New(ctx, body any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockcompletionsAPI)(nil).New), varargs...)
}
