// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/acai-travel/tech-challenge/internal/chat (interfaces: Assistant)
//
// Generated by this command:
//
//	mockgen -destination=mock_assistant_test.go -package=chat github.com/acai-travel/tech-challenge/internal/chat Assistant
//

// Package chat is a generated GoMock package.
package chat

import (
	context "context"
	reflect "reflect"

	model "github.com/acai-travel/tech-challenge/internal/chat/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAssistant is a mock of Assistant interface.
type MockAssistant struct {
	ctrl     *gomock.Controller
	recorder *MockAssistantMockRecorder
	isgomock struct{}
}

// MockAssistantMockRecorder is the mock recorder for MockAssistant.
type MockAssistantMockRecorder struct {
	mock *MockAssistant
}

// NewMockAssistant creates a new mock instance.
func NewMockAssistant(ctrl *gomock.Controller) *MockAssistant {
	mock := &MockAssistant{ctrl: ctrl}
	mock.recorder = &MockAssistantMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAssistant) EXPECT() *MockAssistantMockRecorder {
	return m.recorder
}

// Reply mocks base method.
func (m *MockAssistant) Reply(ctx context.Context, conv *model.Conversation) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reply", ctx, conv)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reply indicates an expected call of Reply.
func (mr *MockAssistantMockRecorder) Reply(ctx, conv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reply", reflect.TypeOf((*MockAssistant)(nil).Reply), ctx, conv)
}

// Title mocks base method.
func (m *MockAssistant) Title(ctx context.Context, conv *model.Conversation) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Title", ctx, conv)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Title indicates an expected call of Title.
func (mr *MockAssistantMockRecorder) Title(ctx, conv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Title", reflect.TypeOf((*MockAssistant)(nil).Title), ctx, conv)
}
